### ISSUE TITLE
Bilder im schwebenden Fenster werden nicht angezeigt

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#61]
Die Fotos der Schüler werden in Version 3.8.1 im schwebenden Fenster (Skalierung 120%) nicht angezeigt.

**Comment by FPfotenhauer** [comment]
Braucht man das Fenster eigentlich noch?

**Comment by Kluesenerm** [comment]
Ja. Wir nutzen es bei Konferenzen. Ist sehr nützlich für mich als Schulleitung und viele Kolleginnen und Kollegen wünschen es sich auch.

**Comment by JuergenRichter** [comment]
In Version 3.0.9 korrigiert

**Comment by Raffenberg** [comment]
Nach dem Start werden bei mir die Bilder zunächst gar nicht angezeigt. Nach einiger Zeit wird bei allen Schülern immer das gleiche Bild einer Schülerin angezeigt. Dies betrifft sowohl das schwebende Fenster, als auch das Bild in der Rubrik "aktueller Schüler".

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren. Habe allerdings nur eine SQLite-DB mit einigen Bildern, da funktioniert es einwandfrei.

**Comment by Raffenberg** [comment]
Hallo Herr Richter,
anbei ein Video im Zip, welches das Problem zeigt (stark verkleinert). Es handelt sich um den Import einer Originaldatenbank.

[Video_2021-02-18_214002.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6006000/Video_2021-02-18_214002.zip)

**Comment by JuergenRichter** [comment]
Wir haben da jetzt noch eine Änderung gemacht. Bisher war es so, dass für die Fotodarstellung im Hauptfenster und im separaten Fenster jeweils eine Dekodierung von Base64 nach jpg durchgeführt wurde. Davon ist aber die für das separate Fenster eigentlich überflüssig, da ja die Dekodierung schon für das Hauptfenster gemacht wurde. Bitte mal mit der Version 3.0.11 testen, falls es damit immer noch nicht funktioniert, wäre es hilfreich, mal die Datenbank (als MariaDB-Dump) zu bekommen.

**Comment by Raffenberg** [comment]
Hallo Herr Richter,haben Sie einen Downloadlink für die neuste Version Schild3.0? Dann teste ich das aus. Mit freundlichen Grüßen Jens RaffenbergFachberaterMobil: 01577 - 3591422Tel: 02051 - 41968-36fb.raffenberg@gmail.com Von: JuergenRichterGesendet: Freitag, 19. Februar 2021 11:41An: SVWS-NRW/Schild3-BetaTestCc: Raffenberg; CommentBetreff: Re: [SVWS-NRW/Schild3-BetaTest] Bilder im schwebenden Fenster werden nicht angezeigt (#61) Wir haben da jetzt noch eine Änderung gemacht. Bisher war es so, dass für die Fotodarstellung im Hauptfenster und im separaten Fenster jeweils eine Dekodierung von Base64 nach jpg durchgeführt wurde. Davon ist aber die für das separate Fenster eigentlich überflüssig, da ja die Dekodierung schon für das Hauptfenster gemacht wurde. Bitte mal mit der Version 3.0.11 testen, falls es damit immer noch nicht funktioniert, wäre es hilfreich, mal die Datenbank (als MariaDB-Dump) zu bekommen.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
